FROM oven/bun:1

WORKDIR /app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./turbo.json ./turbo.json
COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json

COPY ./apps/backend ./apps/backend

RUN apt-get update -y && apt-get install -y openssl

RUN bun install
WORKDIR /app/packages/db
RUN bunx prisma generate --schema=./prisma/schema.prisma



EXPOSE 8080

CMD ["bun","run","start"]
